/* Testnotizen: genug fuer LSA (ab 25 Notizen), vier klar getrennte Themen. */
module.exports = [
  ['Espresso schmeckt sauer', 'kaffee', 'Der Espresso lief in 18 Sekunden durch, viel zu schnell. Mahlgrad feiner stellen.'],
  ['', 'kaffee', 'Neue Bohnen von der Roesterei geholt. Mittlere Roestung, Herkunft Kolumbien.'],
  ['Siebtraeger entkalken', 'kaffee, haushalt', 'Die Maschine braucht eine Entkalkung. Zitronensaeure tut es angeblich genauso.'],
  ['Milchschaum', 'kaffee', 'Wird nie so feinporig wie im Cafe. Kanne vorkuehlen und die Duese knapp unter die Oberflaeche halten.'],
  ['Mahlgrad Notizen', 'kaffee', 'Bei der Kolumbien-Roestung Stufe 12. Immer erst nach zwei Tagen Rastzeit einstellen.'],
  ['Crema zu hell', 'kaffee', 'Wenn die Crema hell und duenn bleibt, ist der Kaffee zu alt oder das Wasser zu kuehl.'],
  ['Tamper Druck', 'kaffee', 'Gleichmaessig andruecken ist wichtiger als fest. Schief getampt heisst Kanalbildung.'],
  ['Reinigung Routine', 'kaffee, haushalt', 'Einmal die Woche Bruehgruppe mit Blindsieb und Pulver durchspuelen.'],

  ['Halbmarathon im Oktober', 'laufen', 'Anmeldung ist raus. Zwoelf Wochen Zeit, Ziel unter zwei Stunden.'],
  ['', 'laufen', 'Intervalltraining heute: sechs mal 800 Meter, dazwischen zwei Minuten Trabpause.'],
  ['Regeneration unterschaetzt', 'laufen, gesundheit', 'Nach harten Einheiten einen Tag komplett ruhen. Schlaf bringt mehr als jede Faszienrolle.'],
  ['Laufschuhe durch', 'laufen', 'Nach etwa 800 Kilometern ist die Daempfung platt. Knie meldet sich.'],
  ['Trainingsplan Woche 3', 'laufen', 'Montag ruhig acht Kilometer, Mittwoch Tempo, Sonntag langer Lauf.'],
  ['Wettkampf Ernaehrung', 'laufen', 'Am Vorabend Nudeln, morgens nur eine Kleinigkeit. Gel ab Kilometer zehn.'],
  ['Pace Gefuehl', 'laufen', 'Zu schnell angegangen. Die ersten drei Kilometer bewusst langsamer.'],
  ['Dehnen bringt wenig', 'laufen, gesundheit', 'Statisches Dehnen vor dem Lauf macht eher schlapp. Lieber einlaufen.'],

  ['Plugin Idee: Toss', 'obsidian, idee', 'Notizen reinwerfen, ohne Ordner und ohne Titel. Verbindungen findet das Plugin selbst.'],
  ['', 'obsidian', 'Ein Obsidian Plugin braucht nur manifest.json und main.js. Kein Build noetig.'],
  ['Markdown bleibt lesbar', 'obsidian, idee', 'Das Format bleibt eine normale Datei. Auch ohne Plugin muss der Vault nutzbar sein.'],
  ['Semantische Suche lokal', 'obsidian, idee', 'Eine Dimensionsreduktion ueber die Term-Dokument-Matrix findet verwandte Begriffe.'],
  ['Mobile zuerst', 'obsidian, idee', 'Die Oberflaeche muss auf dem Telefon funktionieren, einhaendig.'],
  ['Suchindex im Speicher', 'obsidian, idee', 'Der Index gehoert in den Plugin-Ordner, nicht in den Vault. Er ist nur ein Cache.'],
  ['Keine Ordner mehr', 'obsidian, idee', 'Ordner sind eine Entscheidung beim Schreiben. Genau die will ich mir sparen.'],
  ['Tags optional halten', 'obsidian, idee', 'Wenn Tags Pflicht werden, schreibe ich weniger auf. Also bleiben sie freiwillig.'],

  ['Tomaten auf dem Balkon', 'garten', 'Die Pflanzen brauchen mehr Wasser als gedacht, bei Hitze zweimal taeglich giessen.'],
  ['', 'garten', 'Kraeuter im Topf: Basilikum geht ein, Rosmarin und Thymian kommen mit Trockenheit klar.'],
  ['Duenger Rhythmus', 'garten', 'Alle zwei Wochen fluessig ins Wasser. Zu viel und die Pflanze schiesst ins Kraut.'],
  ['Schnecken am Balkon', 'garten', 'Kupferband um die Toepfe hilft. Absammeln am Abend ist die zweitbeste Loesung.'],
  ['Ernte erste Woche', 'garten', 'Die ersten reifen Fruechte geerntet, deutlich mehr Geschmack als gekauft.'],
  ['Aussaat Zeitpunkt', 'garten', 'Ab Maerz auf der Fensterbank vorziehen, ab Mai nach draussen.'],
  ['Wasserfilter', 'kaffee', 'Der Kalk setzt sich sonst in der Bruehgruppe fest. Die Maschine tropft dann nur noch.'],
  ['Muehle vor Maschine', 'kaffee', 'Wer sparen muss, spart an der Maschine, nicht an der Muehle. Ohne gleichmaessiges Pulver hilft keine Bruehtechnik.'],
  ['Vorbereitung Rennen', 'laufen', 'Zwei Wochen vorher Umfang runter, Intensitaet halten. Startnummer am Vorabend rauslegen.'],
  ['Puls im langen Lauf', 'laufen', 'Im langen Lauf den Puls unter 145 halten, sonst wird die Woche danach zaeh.'],
  ['Aehnlichkeit statt Struktur', 'obsidian, idee', 'Zwei Notizen gehoeren zusammen, wenn sie vom Selben handeln. Das kann die Maschine schaetzen.'],
  ['Einhaendig bedienbar', 'obsidian, idee', 'Alles Wichtige muss der Daumen erreichen. Deshalb das Eingabefeld oben und die Liste darunter.'],
  ['Giesskanne vergessen', 'garten', 'Drei Tage weg gewesen, die Erde war knochentrocken. Ein Bewaesserungssystem waere das Geld wert.'],
  ['Balkon im Sommer', 'garten', 'Bei Hitze brauchen die Pflanzen im Topf zweimal taeglich Wasser, sonst haengen die Blaetter.'],
];
